---
name: Test documentation

env:
  CI_FORCE_COLORS_POETRY: --ansi
  CI_FORCE_COLORS_SPHINX: --color

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

  push:
    tags:
      - "!*"
    branches:
      - main
      - "test-me-*"

  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Tests on ${{ matrix.os }} with default python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Display Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Set up Homebrew
        if: runner.os == 'macOS'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install enchant on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install enchant

      - name: Run tests with tox except linkcheck
        if: runner.os != 'Linux'
        run: tox -n docs
        env:
          TOX_SKIP_ENV: docs-test-linkcheck

      - name: Run all tests with tox
        if: runner.os == 'Linux'
        run: tox -n docs
