---
name: QA

env:
  CI_FORCE_COLORS_PRE_COMMIT: --color always

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

  push:
    tags:
      - "!*"
    branches:
      - main
      - "test-me-*"

  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Run QA Tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Display Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox poetry

      - name: Run pre-commit with tox
        run: tox -e pre-commit-run
